### ISSUE TITLE
use cases

### ISSUE THREAD

**Issue by turgs** [SamSaffron/lru_redux#13]
Hi Sam, granted this isn't the best use an a "issue" but i'm wondering if you have an example of how you use this gem with discourse?

I've seen your presentation Off The Rails https://www.youtube.com/watch?v=aP5NNkzb4og but didn't really follow what the benefit of using LRU Cache is in web apps.

Do you have a simple example of where this could be most commonly used?
Thanks
Tim

**Comment by SamSaffron** [comment]
sure, you can see the usages in Discourse

https://github.com/discourse/discourse/search?utf8=%E2%9C%93&q=LruRedux&type=Code

inflector and translation is monkey patched to make it a lot faster, in category where we want to ensure memory is capped we use it as well
