### ISSUE TITLE
Monitoring/Stats?

### ISSUE THREAD

**Issue by tcrayford** [SamSaffron/lru_redux#15]
Is there a reasonable mechanism for monitoring the cache hit ratio of any of the `lru_redux` caches? I can of course, monitor using booleans etc at the callsite, but it's kinda inconvenient if there are plenty of them.

Would you be interested in a patch that adds stats somehow?

**Comment by SamSaffron** [comment]
I would inherit off it and implement counting there, super duper picky
about decreasing any performance here.

**Comment by tcrayford** [comment]
Fair. Thanks.
