### ISSUE TITLE
Eviction Callback

### ISSUE THREAD

**Issue by tboyko** [SamSaffron/lru_redux#18]
Is there any means for executing a callback (lambda/proc/block) when an item is automatically evicted from the cache due to cache size? This is useful in scenarios where necessary cleanup has to occur before dereferencing an object, such as for network connection related matters.

**Comment by SamSaffron** [comment]
My recommendation here for any fancy stuff like this would be to just copy and paste https://github.com/SamSaffron/lru_redux/blob/master/lib/lru_redux/cache.rb and implement it there for your project. The intention behind lru_redux is to be the fastest out there and adding extra checks and callbacks will slow down the implementation

**Comment by tboyko** [comment]
Fair enough.

On an unrelated note, thanks for your contributions to documented ruby memory management knowledge. Much appreciated.
