### ISSUE TITLE
TTL cache name space feedback.

### ISSUE THREAD

**Issue by Seberius** [SamSaffron/lru_redux#9]
With the addition of a new cache I wanted to get some feedback on the current working name for the TTL cache. I also included an alternative naming scheme to consider.
```
# Current
LruRedux::Cache
LruRedux::ThreadSafeCache

# Working TTL names
LruRedux::TtlCache
LruRedux::ThreadSafeTtlCache

# Alternative
LruRedux::LRU::Cache
LruRedux::LRU::ThreadSafeCache

LruRedux::TTL::Cache
LruRedux::TTL::ThreadSafeCache
```
If the modularized name space was chosen, the current namespaces `LruRedux::Cache` and `LruRedux::ThreadSafeCache` could be made into a subclass to provide identical functionality (and backwards compatibility) but also raise a warning about the name change.  This is similar to what the 'minitest' gem does if you call `MiniTest::Unit::TestCase` instead of `MiniTest::Test`.

**Comment by SamSaffron** [comment]
Hmm what about simply adding 

```
LruRedux::TTL::Cache
LruRedux::TTL::ThreadSafeCache
```

Its backwards compatible and is fairly clear. The name TtlCache really looks bad to me ... TTLCache also looks bad... so namespacing seems to be the only way to go.

**Comment by SamSaffron** [comment]
(I mean leave the old LruRedux::Cache as is)

**Comment by Seberius** [comment]
That looks good to me.  Thanks
